[package]
name = "microfield-external-consumer"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]
resolver = "2"

[dependencies]
microfield = { path = "../..", default-features = false, features = ["portable"] }

[build-dependencies]
microfield = { path = "../..", default-features = false, features = ["generator"] }
