//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_256_alt_v1";
pub const FIELD_ID: [u8; 32] = [92, 120, 234, 47, 158, 161, 178, 213, 155, 136, 191, 50, 227, 138, 227, 59, 228, 194, 249, 119, 240, 35, 44, 68, 65, 247, 161, 110, 76, 155, 181, 77];
pub const ARTIFACT_ID: [u8; 32] = [136, 172, 11, 210, 38, 150, 208, 43, 192, 245, 82, 39, 1, 213, 57, 139, 22, 15, 143, 169, 245, 57, 65, 146, 23, 160, 179, 5, 114, 162, 40, 195];
pub const DEGREE: usize = 256;
pub const CANONICAL_BYTES: usize = 32;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[256, 16, 3, 1, 0];
