//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_256_alt_v1";
pub const FIELD_ID: [u8; 32] = [92, 120, 234, 47, 158, 161, 178, 213, 155, 136, 191, 50, 227, 138, 227, 59, 228, 194, 249, 119, 240, 35, 44, 68, 65, 247, 161, 110, 76, 155, 181, 77];
pub const ARTIFACT_ID: [u8; 32] = [230, 33, 179, 51, 146, 151, 48, 153, 86, 13, 148, 84, 15, 222, 92, 86, 78, 223, 141, 59, 28, 187, 70, 118, 4, 192, 248, 211, 147, 71, 17, 222];
pub const DEGREE: usize = 256;
pub const CANONICAL_BYTES: usize = 32;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[256, 16, 3, 1, 0];
