//! Pure deterministic artifact rendering.

use std::fmt::Write as _;

use serde::Serialize;

use crate::spec::{
    error::GenerationError,
    identity::{artifact_bundle_digest, content_digest},
    model::{GeneratedArtifacts, GeneratedFile, GenerationPlan, ValidatedFieldSpec},
};

/// Stateless renderer for portable version-1 generated files.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ArtifactGenerator;

impl ArtifactGenerator {
    /// Renders a complete immutable artifact set without performing I/O.
    ///
    /// # Errors
    ///
    /// Returns an error for a mismatched plan, serialization failure or
    /// invalid generated path.
    pub fn generate(
        &self,
        validated: &ValidatedFieldSpec,
        plan: &GenerationPlan,
    ) -> Result<GeneratedArtifacts, GenerationError> {
        if validated.field_id() != plan.field_id() {
            return Err(GenerationError::MismatchedPlan);
        }

        let normalized = validated.normalized();
        let metadata = ArtifactMetadata {
            schema: 1,
            field_name: normalized.name(),
            field_id: validated.field_id(),
            artifact_id: plan.artifact_id(),
            generator_version: env!("CARGO_PKG_VERSION"),
            reproducible: true,
        };

        let mut files = vec![
            GeneratedFile::new("certificate.json", pretty_json(validated.certificate())?)?,
            GeneratedFile::new("descriptor.json", pretty_json(normalized.descriptor())?)?,
            GeneratedFile::new(
                "field.rs",
                render_field_constants(validated, plan).into_bytes(),
            )?,
            GeneratedFile::new("generation-plan.json", pretty_json(plan)?)?,
            GeneratedFile::new("metadata.json", pretty_json(&metadata)?)?,
            GeneratedFile::new(
                "normalized.toml",
                normalized.canonical_toml().as_bytes().to_vec(),
            )?,
        ];
        files.sort_unstable_by(|lhs, rhs| lhs.relative_path().cmp(rhs.relative_path()));
        let bundle_files = files
            .iter()
            .map(|file| BundleFile {
                path: file.relative_path(),
                bytes: file.contents().len(),
                sha256: content_digest(file.contents()),
            })
            .collect::<Vec<_>>();
        let bundle_descriptor = serde_json::to_vec(&bundle_files)
            .map_err(|error| GenerationError::Serialization(error.to_string()))?;
        let bundle_digest = artifact_bundle_digest(&bundle_descriptor);
        let bundle = ArtifactBundleManifest {
            schema: 1,
            artifact_id: plan.artifact_id(),
            bundle_digest,
            files: &bundle_files,
        };
        files.push(GeneratedFile::new("bundle.json", pretty_json(&bundle)?)?);

        GeneratedArtifacts::new(
            normalized.name().to_owned(),
            validated.field_id(),
            plan.artifact_id(),
            bundle_digest,
            files,
        )
    }
}

#[derive(Serialize)]
struct ArtifactMetadata<'a> {
    schema: u32,
    field_name: &'a str,
    field_id: crate::FieldId,
    artifact_id: crate::ArtifactId,
    generator_version: &'static str,
    reproducible: bool,
}

#[derive(Serialize)]
struct ArtifactBundleManifest<'a> {
    schema: u32,
    artifact_id: crate::ArtifactId,
    bundle_digest: crate::ArtifactBundleDigest,
    files: &'a [BundleFile<'a>],
}

#[derive(Serialize)]
struct BundleFile<'a> {
    path: &'a str,
    bytes: usize,
    sha256: String,
}

fn pretty_json<T: Serialize>(value: &T) -> Result<Vec<u8>, GenerationError> {
    let mut bytes = serde_json::to_vec_pretty(value)
        .map_err(|error| GenerationError::Serialization(error.to_string()))?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn render_field_constants(validated: &ValidatedFieldSpec, plan: &GenerationPlan) -> String {
    let normalized = validated.normalized();
    let descriptor = normalized.descriptor();
    let mut source = String::from(
        "//! Deterministic constants generated by `microfield-gen`.\n\
         //!\n\
         //! This file contains certified data only. Runtime field types consume\n\
         //! these constants without placing generated logic in the hot path.\n\n",
    );
    writeln!(
        source,
        "pub const FIELD_NAME: &str = {:?};",
        normalized.name()
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "pub const FIELD_ID: [u8; 32] = {:?};",
        validated.field_id().as_bytes()
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "pub const ARTIFACT_ID: [u8; 32] = {:?};",
        plan.artifact_id().as_bytes()
    )
    .expect("writing to String cannot fail");
    writeln!(source, "pub const DEGREE: usize = {};", descriptor.degree())
        .expect("writing to String cannot fail");
    writeln!(
        source,
        "pub const CANONICAL_BYTES: usize = {};",
        descriptor.canonical_bytes()
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "pub const MODULUS_EXPONENTS_DESC: &[usize] = &{:?};",
        descriptor.modulus_exponents()
    )
    .expect("writing to String cannot fail");
    source
}
