//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_128_v1";
pub const FIELD_ID: [u8; 32] = [72, 37, 182, 213, 96, 110, 52, 175, 50, 114, 42, 74, 106, 150, 208, 74, 30, 33, 51, 123, 224, 251, 115, 74, 219, 156, 105, 249, 185, 215, 125, 49];
pub const ARTIFACT_ID: [u8; 32] = [55, 123, 143, 84, 2, 176, 87, 218, 227, 126, 205, 173, 27, 228, 114, 89, 216, 226, 69, 85, 167, 148, 250, 164, 101, 53, 236, 174, 41, 139, 85, 140];
pub const DEGREE: usize = 128;
pub const CANONICAL_BYTES: usize = 16;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[128, 7, 2, 1, 0];
