//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_128_v1";
pub const FIELD_ID: [u8; 32] = [72, 37, 182, 213, 96, 110, 52, 175, 50, 114, 42, 74, 106, 150, 208, 74, 30, 33, 51, 123, 224, 251, 115, 74, 219, 156, 105, 249, 185, 215, 125, 49];
pub const ARTIFACT_ID: [u8; 32] = [207, 129, 159, 27, 220, 63, 235, 144, 182, 96, 37, 29, 176, 160, 63, 14, 83, 19, 188, 162, 89, 14, 116, 153, 17, 215, 251, 247, 136, 25, 133, 252];
pub const DEGREE: usize = 128;
pub const CANONICAL_BYTES: usize = 16;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[128, 7, 2, 1, 0];
