//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_128_v1";
pub const FIELD_ID: [u8; 32] = [72, 37, 182, 213, 96, 110, 52, 175, 50, 114, 42, 74, 106, 150, 208, 74, 30, 33, 51, 123, 224, 251, 115, 74, 219, 156, 105, 249, 185, 215, 125, 49];
pub const ARTIFACT_ID: [u8; 32] = [174, 117, 134, 76, 15, 15, 108, 146, 37, 8, 28, 234, 41, 245, 235, 85, 64, 238, 173, 202, 101, 233, 243, 35, 101, 165, 186, 58, 4, 81, 208, 106];
pub const DEGREE: usize = 128;
pub const CANONICAL_BYTES: usize = 16;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[128, 7, 2, 1, 0];
