//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_256_hh_v1";
pub const FIELD_ID: [u8; 32] = [107, 98, 254, 166, 139, 150, 143, 212, 248, 195, 154, 79, 105, 183, 143, 113, 76, 128, 133, 139, 29, 15, 102, 126, 197, 166, 61, 68, 23, 180, 60, 168];
pub const ARTIFACT_ID: [u8; 32] = [52, 43, 66, 36, 83, 180, 246, 127, 86, 180, 76, 220, 255, 167, 179, 250, 104, 2, 76, 141, 230, 239, 191, 116, 161, 75, 163, 109, 99, 178, 94, 100];
pub const DEGREE: usize = 256;
pub const CANONICAL_BYTES: usize = 32;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[256, 10, 5, 2, 0];
