//! Deterministic constants generated by `microfield-gen`.
//!
//! This file contains certified data only. Runtime field types consume
//! these constants without placing generated logic in the hot path.

pub const FIELD_NAME: &str = "gf2_256_hh_v1";
pub const FIELD_ID: [u8; 32] = [107, 98, 254, 166, 139, 150, 143, 212, 248, 195, 154, 79, 105, 183, 143, 113, 76, 128, 133, 139, 29, 15, 102, 126, 197, 166, 61, 68, 23, 180, 60, 168];
pub const ARTIFACT_ID: [u8; 32] = [251, 102, 220, 133, 128, 101, 148, 145, 243, 71, 184, 178, 190, 135, 141, 42, 6, 141, 102, 8, 230, 246, 109, 180, 188, 205, 195, 241, 247, 99, 73, 69];
pub const DEGREE: usize = 256;
pub const CANONICAL_BYTES: usize = 32;
pub const MODULUS_EXPONENTS_DESC: &[usize] = &[256, 10, 5, 2, 0];
